apiVersion: v1
kind: Pod
metadata:
  name: llama2-pod
  labels:
    app.kubernetes.io/name: proxy
spec:
  restartPolicy: Never
  schedulerName: default-scheduler
  nodeSelector:
    node.kubernetes.io/instance-type: inf2.xlarge
  containers:
    - name: llama2-inf
      image: "763104351884.dkr.ecr.us-west-2.amazonaws.com/djl-inference:0.25.0-neuronx-sdk2.15.0"
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
          name: http-web-svc
      command: ["djl-serving"]
      args: ["-m", "-e SERVING_LOAD_MODELS=$(SERVING_LOAD_MODELS)", \
             "-e OPTION_ENTRYPOINT=$(OPTION_ENTRYPOINT)", \
             "-e OPTION_MODEL_ID=$(OPTION_MODEL_ID)", \
             "-e OPTION_BATCH_SIZE=$(OPTION_BATCH_SIZE)", \
             "-e OPTION_NEURON_OPTIMIZE_LEVEL=$(OPTION_NEURON_OPTIMIZE_LEVEL)", \
             "-e OPTION_TENSOR_PARALLEL_DEGREE=$(OPTION_TENSOR_PARALLEL_DEGREE)", \
             "-e OPTION_N_POSITIONS=$(OPTION_N_POSITIONS)", \
             "-e OPTION_DTYPE=$(OPTION_DTYPE)"]
      env:
        - name: SERVING_LOAD_MODELS
          value: "test::Python=/opt/ml/model"
        - name: OPTION_ENTRYPOINT
          value: "djl_python.transformers_neuronx"
        - name: OPTION_MODEL_ID
          value: "PY007/TinyLlama-1.1B-intermediate-step-480k-1T"
        - name: OPTION_BATCH_SIZE
          value: "4"
        - name: OPTION_NEURON_OPTIMIZE_LEVEL
          value: "1"
        - name: OPTION_TENSOR_PARALLEL_DEGREE
          value: "2"
        - name: OPTION_N_POSITIONS
          value: "512"
        - name: OPTION_DTYPE
          value: "fp16"

      volumeMounts:
        - name: model
          mountPath: "/dev/shm"
      resources:
        limits:
          aws.amazon.com/neuron: 1
  volumes:
    - name: model
      emptyDir:

---
apiVersion: v1
kind: Service
metadata:
  name: llama2-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http-web-svc
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
