---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: llama2
  region: us-west-2
  version: "1.29"

managedNodeGroups:
- name: neuron
  ami: ami-09a2da17547239748
  amiFamily: AmazonLinux2
  iam:
    attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
  instanceType: inf2.xlarge
  desiredCapacity: 1
  overrideBootstrapCommand: |
     #!/bin/bash
     /etc/eks/bootstrap.sh llama2
  volumeSize: 80
  ssh:
     allow: true
     publicKeyPath: ~/.ssh/id_rsa.pub

